spring:
  cloud:
    gateway:
      routes:
        - id: index12306-user-aggregation-service
          uri: lb://index12306-aggregation${unique-name:}-service/api/user-service/** #负载均衡到哪里  /api/user-service/**表示请求必须和这个匹配，和predicates设置相同
          predicates:
            - Path=/api/user-service/**  #过滤哪些请求
          filters:  #转发请求前要做的过滤操作 过滤器链
            - name: TokenValidate
              args: # 转发请求时携带的参数
                blackPathPre:
                  - /api/user-service/passenger
                  - /api/user-service/query
                  - /api/user-service/logout
                  - /api/user-service/deletion

        - id: index12306-ticket-aggregation-service
          uri: lb://index12306-aggregation${unique-name:}-service/api/ticket-service/**
          predicates:
            - Path=/api/ticket-service/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/ticket-service/ticket/purchase
                  - /api/ticket-service/ticket/pay/query
                  - /api/ticket-service/ticket/cancel

        - id: index12306-pay-aggregation-service
          uri: lb://index12306-aggregation${unique-name:}-service/api/pay-service/**
          predicates:
            - Path=/api/pay-service/**

        - id: index12306-order-aggregation-service
          uri: lb://index12306-aggregation${unique-name:}-service/api/order-service/**
          predicates:
            - Path=/api/order-service/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/order-service/order/ticket/query
                  - /api/order-service/order/ticket/page
                  - /api/order-service/order/ticket/self/page
